version: '3.9'

services:
  server:
    image: nginx:1.21.1
    container_name: nginx
    ports:
      - 80:80
    networks:
      - net
    volumes:
      - ./confs/servers:/etc/nginx/conf.d/
      - ./backend:/var/www/html

  backend-jukebox:
    build: ./backend
    container_name: backend-jukebox
    networks:
      - net
    volumes:
      - ./backend:/var/www/html

  frontend-jukebox: 
    build: ./frontend
    container_name: frontend-jukebox
    ports:
      - 8080:8080
    networks:
      - net
    volumes:
      - ./frontend:/app
    command: ['npm', 'run', 'serve']

  mysql:
    image: mysql:5.7
    container_name: mysql-jukebox
    volumes: 
      - ./confs/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jukebox
    ports:
      - 3306:3306
    networks: 
      - net

networks: 
  net:
    driver: bridge
